import re
import json

with open('index.html', 'r') as f:
    html = f.read()

# 1. Fix CSS for onboarding
css_old = "background: rgba(5,5,5,0.85) !important;\n    backdrop-filter: blur(16px) !important;"
css_new = "background: rgba(5,5,5,0.3) !important;\n    backdrop-filter: blur(6px) !important;"
html = html.replace(css_old, css_new)

# 2. Fix the smart brain logic
old_handleQuery = """    function handleQuery(q) {
      // Simple routing logic based on keywords
      const lower = q.toLowerCase();
      if (lower.includes('metric') || lower.includes('highlight') || lower.includes('roi')) {
        loadSection('highlights');
      } else if (lower.includes('project') || lower.includes('build')) {
        loadSection('projects');
      } else if (lower.includes('timeline') || lower.includes('journey')) {
        loadSection('timeline');
      } else if (lower.includes('deep') || lower.includes('experience')) {
        loadSection('deep_exp');
      } else if (lower.includes('resume')) {
        loadSection('resume');
      } else if (lower.includes('contact')) {
        loadSection('contact');
      } else {
        speakText(`I'm a static AI construct right now, so I don't have an LLM attached to answer arbitrary questions, but I can navigate you! Try asking for my Resume or Projects.`, fcBody);
      }
    }"""

new_handleQuery = """    function handleQuery(q) {
      const lower = q.toLowerCase();
      
      const intents = {
        'highlights': ['metric', 'highlight', 'roi', 'growth', 'result', 'impact', 'number', 'revenue', 'arr', 'mrr'],
        'projects': ['project', 'build', 'side', 'experiment', 'hobby', 'app', 'tool'],
        'deep_exp': ['experience', 'work', 'job', 'history', 'times internet', 'vahdam', 'career', 'role'],
        'timeline': ['timeline', 'journey', 'path', 'story'],
        'intro': ['about', 'who are you', 'intro', 'bio'],
        'contact': ['contact', 'email', 'message', 'reach', 'talk', 'chat with anchit']
      };
      
      let matchedSection = null;
      for (const [section, keywords] of Object.entries(intents)) {
        if (keywords.some(kw => lower.includes(kw))) {
          matchedSection = section;
          break;
        }
      }
      
      if (matchedSection) {
        let msg = '';
        if (matchedSection === 'highlights') msg = "I've pulled up the key metrics and ROI from Anchit's major product launches.";
        if (matchedSection === 'projects') msg = "Loading his AI and side builds. He engineers these end-to-end.";
        if (matchedSection === 'deep_exp') msg = "Navigating to his professional product history across Vahdam and Times Internet.";
        if (matchedSection === 'timeline') msg = "Here is the timeline of his journey from engineering to product management.";
        if (matchedSection === 'intro') msg = "Here is a quick overview of who Anchit is.";
        if (matchedSection === 'contact') msg = "Bringing up his contact details so you can reach out directly.";
        
        speakText(msg, fcBody);
        setTimeout(() => loadSection(matchedSection), 100);
      } else {
        speakText(`I am the autonomous brain navigating this OS. Ask me to show you his metrics, side projects, work history, or contact details, and I will drive the UI for you.`, fcBody);
      }
    }"""

html = html.replace(old_handleQuery, new_handleQuery)

# 3. Update the metrics text to be more explicit about cause-and-effect
# Need to extract the JSON payload
payload_match = re.search(r'<script type="application/json" id="sectionsDataPayload">\n(.*?)\n</script>', html, re.DOTALL)
if payload_match:
    payload_str = payload_match.group(1)
    data = json.loads(payload_str)
    
    # Update Highlights
    data['highlights'] = data['highlights'].replace(
        '<div class="label">MRR growth · ₹15L → ₹80L · ET Prime Assisted Sales at Times Internet</div>',
        '<div class="label">MRR Growth (₹15L → ₹80L) driven by scaling the ET Prime Assisted Sales channel via a custom AI telesuite</div>'
    ).replace(
        '<div class="label">Incremental ARR · ET Markets revamp across Web, mWeb, Android, iOS</div>',
        '<div class="label">Incremental ARR generated by redesigning the ET Markets cross-platform funnel (Web/iOS/Android)</div>'
    ).replace(
        '<div class="label">Product ratings lift at Vahdam India via cross-functional experiments</div>',
        '<div class="label">Global App Rating Lift via cross-functional UX and CRM experiments across US, UK, and EU markets</div>'
    ).replace(
        '<div class="label">Products shipped · 7 at work + 5 AI side projects, all live</div>',
        '<div class="label">Total Products Architected & Shipped end-to-end (7 corporate + 5 AI side builds)</div>'
    )
    
    # Update deep_exp
    data['deep_exp'] = data['deep_exp'].replace(
        '<div class="label">MRR growth · ET Prime Assisted Sales</div>',
        '<div class="label">MRR growth by scaling ET Prime Assisted Sales via AI</div>'
    ).replace(
        '<div class="label">Incremental ARR · ET Markets revamp</div>',
        '<div class="label">Incremental ARR via ET Markets cross-platform redesign</div>'
    ).replace(
        '<div class="label">Product ratings · Vahdam India</div>',
        '<div class="label">Product ratings lift via Global UX/CRM experiments</div>'
    )

    new_payload = json.dumps(data, indent=2)
    # the original was not indented nicely, but it's fine
    
    html = html[:payload_match.start(1)] + new_payload + html[payload_match.end(1):]
    
with open('index.html', 'w') as f:
    f.write(html)

print("Applied smart brain fixes, reduced background blur, and explicit metrics.")
