#!/usr/bin/env bash
# setup-env.sh — set every optional API key this site uses, in Vercel, in one pass.
#
# Run it on YOUR machine (it needs your Vercel login). It prompts for each key
# silently, sends it straight to Vercel, and never echoes it, logs it, or writes
# it to disk. Press Enter to skip any key — every feature degrades gracefully
# without it, so a partial setup is fine.
#
#   bash scripts/setup-env.sh                 # production (default)
#   TARGET=preview bash scripts/setup-env.sh  # preview environment
#
# Keys cannot be generated by this (or any) script — each is minted in that
# vendor's dashboard after you log in there. The URL to get each one is printed
# next to the prompt.

set -uo pipefail

TARGET="${TARGET:-production}"
VERCEL="npx --yes vercel@latest"

echo "→ Setting environment variables for: $TARGET"
echo "  Values are read silently and piped to Vercel. Enter = skip."
echo

# Ensure we're linked to the right Vercel project before writing anything.
if ! $VERCEL whoami >/dev/null 2>&1; then
  echo "You are not logged in to Vercel. Running login…"
  $VERCEL login || { echo "✗ Vercel login failed."; exit 1; }
fi
if [ ! -f .vercel/project.json ]; then
  echo "This folder is not linked to a Vercel project. Running link…"
  $VERCEL link || { echo "✗ Vercel link failed."; exit 1; }
fi

set_key() {
  local name="$1" desc="$2" url="$3" value=""
  echo "── $name"
  echo "   $desc"
  echo "   get it: $url"
  read -r -s -p "   value (Enter to skip): " value
  echo
  if [ -z "$value" ]; then echo "   ↳ skipped"; echo; return 0; fi
  # printf (not echo) so no trailing newline is stored in the value.
  if printf '%s' "$value" | $VERCEL env add "$name" "$TARGET" >/dev/null 2>&1; then
    echo "   ↳ set ✓"
  else
    echo "   ↳ could not set (it may already exist — remove it first:"
    echo "      $VERCEL env rm $name $TARGET )"
  fi
  unset value
  echo
}

echo "=== Voice (cloned + Indian languages) ==="
set_key ELEVENLABS_API_KEY  "Your cloned voice (needs a plan with instant voice cloning)." "https://elevenlabs.io/app/settings/api-keys"
set_key ELEVENLABS_VOICE_ID "The cloned voice id — run: ELEVENLABS_API_KEY=… node scripts/elevenlabs-clone.mjs" "printed by that script"
set_key SARVAM_API_KEY      "Native Indian-language TTS (Hindi, Tamil, Telugu, Kannada, Malayalam). STOCK voice, not your clone — Sarvam's API has no cloning. Runs last in the cascade. See SARVAM.md." "https://dashboard.sarvam.ai/"

echo "=== Video avatar (pick either) ==="
set_key DID_API_KEY   "D-ID talking head (paid, credit-metered)." "https://studio.d-id.com/account-settings"
set_key AVATAR_API_URL "Self-hosted open-source avatar endpoint (e.g. LongCat-Video-Avatar 1.5 on Replicate/Modal/RunPod). Free alternative to D-ID; tried first when set." "your own GPU endpoint URL"
set_key AVATAR_API_KEY "Bearer token for that endpoint (optional)." "your endpoint's token"
set_key DID_SOURCE_URL "URL of a CLOSE, FRONT-FACING headshot (no sunglasses). Required for a good avatar — a logo/poster or full-body shot will not animate." "e.g. https://anchit-tandon.com/assets/headshot.jpg"

echo "=== Models ==="
set_key ANTHROPIC_API_KEY "Claude — powers the chat clone, the How-To cascade and per-step tutorial lookup." "https://console.anthropic.com/settings/keys"
set_key GEMINI_API_KEY    "Gemini — a provider in the lifecycle + How-To cascades." "https://aistudio.google.com/apikey"
set_key OPENAI_API_KEY    "OpenAI — cascade provider (optional)." "https://platform.openai.com/api-keys"
set_key META_API_URL      "Meta Model API base URL (Muse Spark, public preview) — the provider stays off unless this AND the key are set." "https://ai.meta.com/ (Model API docs)"
set_key META_API_KEY      "Meta Model API key." "https://ai.meta.com/"

echo "=== Google Vertex AI Agent Builder (optional; answers the chat first when set) ==="
set_key GOOGLE_PROJECT_ID     "GCP project id that owns the agent." "https://console.cloud.google.com/"
set_key GOOGLE_AGENT_ENGINE   "Agent Builder app / engine id." "https://console.cloud.google.com/gen-app-builder"
set_key GOOGLE_AGENT_LOCATION "Agent location: global (default), eu or us." "optional"
set_key GOOGLE_SERVICE_ACCOUNT_JSON "The service-account JSON, pasted verbatim (needs Discovery Engine access). A token is minted from it automatically." "https://console.cloud.google.com/iam-admin/serviceaccounts"
set_key GOOGLE_AGENT_URL      "OPTIONAL alternative: a full endpoint URL, used verbatim — for Dialogflow CX, a Reasoning Engine or an ADK service instead of a Discovery Engine app." "your agent's endpoint"

echo "=== Optional extras ==="
set_key CARTESIA_API_KEY "Cartesia TTS (another voice-clone tier in the cascade)." "https://play.cartesia.ai/keys"
set_key FISH_API_KEY     "Fish Audio TTS (free developer tier)." "https://fish.audio/go-api/"
set_key GROQ_API_KEY     "Groq — fast free-tier LLM for the lifecycle cascade." "https://console.groq.com/keys"

echo "Done. Redeploy for the new values to take effect:"
echo "  $VERCEL --prod"
echo
echo "Verify afterwards:"
echo "  curl -s https://anchit-tandon.com/api/tts?debug=1   # which voice providers are wired"
echo "  curl -s https://anchit-tandon.com/api/avatar        # which avatar engine is active"
