// /api/cascade — turn "how do I X" into a REAL, specific, step-by-step guide.
//
// WHY THIS FILE EXISTS
//   The How-To Engine shipped with its own api/cascade.ts inside
//   side-husle/how-to-1/, which Vercel never deploys — only the root api/
//   folder becomes functions. So every request 404'd, the client caught it, and
//   it rendered its offline placeholder: "Get set up / Do the first move /
//   Avoid the common trap", which is a template with the task name pasted in
//   and tells nobody how to do anything. That is what was live.
//
// The guide's `edges` are what the flow diagram draws, so the model is asked
// for them directly — the flowchart is generated by the model, not inferred
// from a straight line afterwards.

// Read per request, not at module load. A module-scope capture is fixed for the
// lifetime of the warm function, so a key added or rotated in the dashboard
// would not take effect until the instance recycled — and it makes the handler
// untestable, which is how the untested path got shipped in the first place.
const key = () => process.env.ANTHROPIC_API_KEY;

// A chain, not a single id. step-video pins `claude-opus-4-8` and has been
// silently returning its fallback in production because that call fails — the
// response carried the "request failed" cache header rather than the "no key"
// one. Trying several and reporting which answered means a wrong id degrades
// to a slower success instead of an invisible placeholder.
const MODELS = [
  process.env.CASCADE_MODEL,
  'claude-sonnet-5',
  'claude-opus-5',
  'claude-sonnet-4-6',
  'claude-haiku-4-5-20251001',
].filter(Boolean);

const SYSTEM = `You write genuinely useful step-by-step guides for people who may be doing the task for the very first time.

RULES
- Be SPECIFIC to the task. Never write filler like "get set up", "do the first move" or "avoid the common trap". If the task is switching on a phone, say which button, how long to hold it, and what appears on screen.
- Each step is one atomic action a person can do without deciding anything else first.
- 4-7 steps. Titles are 3-7 words, imperative ("Hold the side button").
- detail is 1-2 short sentences of real instruction, including the specific thing to look for or press.
- badge is one of: start, action, watch-out, checkpoint, finish.
- Include at least one "watch-out" naming the actual mistake people make at that point in THIS task.
- edges connect step ids in order. Add an extra labelled edge where a real branch exists (e.g. {"from":"s2","to":"s4","label":"if it does not turn on"}).
- videoPrompt is a short search phrase that would find footage of that exact step.

Reply with ONLY a JSON object, no prose, no markdown fence:
{"summary":"one sentence","difficulty":"trivial|easy|moderate|skilled|expert","estMinutes":number,"steps":[{"id":"s1","index":1,"title":"","detail":"","badge":"start","estSeconds":number,"videoPrompt":""}],"edges":[{"from":"s1","to":"s2","label":""}]}`;

async function callClaude(model, task, signal) {
  const r = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    signal,
    headers: { 'content-type': 'application/json', 'x-api-key': key(), 'anthropic-version': '2023-06-01' },
    body: JSON.stringify({
      model,
      max_tokens: 2000,
      system: SYSTEM,
      messages: [{ role: 'user', content: `Write the guide for: ${task}` }],
    }),
  });
  if (!r.ok) {
    let why = '';
    try { why = (await r.json())?.error?.message || ''; } catch {}
    throw new Error(`${r.status}${why ? ' ' + why.slice(0, 120) : ''}`);
  }
  const data = await r.json();
  const text = (data.content || []).filter((b) => b.type === 'text').map((b) => b.text).join('');
  const m = text.match(/\{[\s\S]*\}/);            // tolerate stray prose or a fence
  if (!m) throw new Error('no JSON in reply');
  return JSON.parse(m[0]);
}

// Normalise whatever the model returned into exactly the shape types.ts
// declares, so a missing field can never reach the UI as `undefined`.
function shape(raw, task) {
  const ok = ['start', 'action', 'watch-out', 'checkpoint', 'finish'];
  const steps = (Array.isArray(raw.steps) ? raw.steps : []).slice(0, 8).map((s, i) => ({
    id: String(s.id || `s${i + 1}`),
    index: i + 1,
    title: String(s.title || '').slice(0, 80),
    detail: String(s.detail || '').slice(0, 400),
    badge: ok.includes(s.badge) ? s.badge : (i === 0 ? 'start' : 'action'),
    estSeconds: Number(s.estSeconds) > 0 ? Number(s.estSeconds) : 45,
    videoPrompt: String(s.videoPrompt || `${task} step ${i + 1}`).slice(0, 160),
  })).filter((s) => s.title && s.detail);
  if (steps.length < 2) throw new Error('too few usable steps');

  const ids = new Set(steps.map((s) => s.id));
  let edges = (Array.isArray(raw.edges) ? raw.edges : [])
    .filter((e) => ids.has(e.from) && ids.has(e.to) && e.from !== e.to)
    .map((e) => ({ from: e.from, to: e.to, label: e.label ? String(e.label).slice(0, 40) : undefined }));
  // Guarantee the spine so the diagram is never a scatter of orphans.
  for (let i = 0; i < steps.length - 1; i++) {
    const a = steps[i].id, b = steps[i + 1].id;
    if (!edges.some((e) => e.from === a && e.to === b)) edges.push({ from: a, to: b });
  }

  const diff = ['trivial', 'easy', 'moderate', 'skilled', 'expert'];
  return {
    task,
    summary: String(raw.summary || '').slice(0, 300) || `How to ${task}.`,
    difficulty: diff.includes(raw.difficulty) ? raw.difficulty : 'easy',
    estMinutes: Number(raw.estMinutes) > 0 ? Math.min(Number(raw.estMinutes), 240) : 5,
    steps,
    edges,
  };
}

module.exports = async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();

  // GET is a diagnostic: is the key present, and which model actually answers?
  // Booleans and model names only — never a key. This exists because the same
  // class of failure hid here for months behind a silent fallback.
  if (req.method === 'GET') {
    if (!key()) return res.status(200).json({ configured: false, reason: 'ANTHROPIC_API_KEY not set', models: MODELS });
    const c = new AbortController(); const t = setTimeout(() => c.abort(), 20000);
    const tried = [];
    try {
      for (const m of MODELS) {
        try { await callClaude(m, 'boil an egg', c.signal); tried.push({ model: m, ok: true }); break; }
        catch (e) { tried.push({ model: m, ok: false, error: String(e.message).slice(0, 140) }); }
      }
    } finally { clearTimeout(t); }
    return res.status(200).json({ configured: true, tried });
  }

  let body = {};
  try { body = typeof req.body === 'string' ? JSON.parse(req.body) : (req.body || {}); } catch {}
  const task = String(body.task || '').replace(/\s+/g, ' ').trim().slice(0, 400);
  if (!task) return res.status(400).json({ error: 'Missing "task"' });
  if (!key()) return res.status(503).json({ error: 'ANTHROPIC_API_KEY is not configured' });

  const c = new AbortController(); const t = setTimeout(() => c.abort(), 45000);
  const attempts = [];
  try {
    for (const model of MODELS) {
      const t0 = Date.now();
      try {
        const guide = shape(await callClaude(model, task, c.signal), task);
        guide.provenance = { models: [model], consensus: 1 };
        const answer = { model, rank: 1, ok: true, latencyMs: Date.now() - t0, guide };
        res.setHeader('Cache-Control', 'no-store');
        return res.status(200).json({ guide, answers: [...attempts, answer], top: [answer] });
      } catch (e) {
        attempts.push({ model, rank: attempts.length + 1, ok: false, latencyMs: Date.now() - t0, error: String(e.message).slice(0, 160) });
      }
    }
    // Every model failed. Say so plainly rather than returning a placeholder
    // dressed as an answer — that is exactly how the useless guide went live.
    return res.status(502).json({ error: 'Every model failed to produce a guide.', answers: attempts });
  } finally { clearTimeout(t); }
};
